import { useEffect, useState } from "react";

import api from "../api/client";
import ReportCard from "../components/ReportCard";

export default function Reports() {
  const [reports, setReports] = useState([]);

  useEffect(() => {
    api.get("/api/analysis/history").then((response) => {
      const withReports = response.data.items
        .filter((item) => item.incident_report)
        .map((item) => ({
          id: item.id,
          severity: item.risk_score >= 70 ? "high" : item.risk_score >= 40 ? "medium" : "low",
          report_text: item.incident_report,
        }));
      setReports(withReports);
    });
  }, []);

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-semibold text-slate-900">Reports</h1>
        <p className="mt-2 text-slate-500">Persisted incident narratives generated by the AI pipeline.</p>
      </div>
      <div className="grid gap-4 md:grid-cols-2">
        {reports.map((report) => (
          <ReportCard key={report.id} report={report} />
        ))}
      </div>
    </div>
  );
}
