import { useEffect, useState } from "react";

import api from "../api/client";
import ReportCard from "../components/ReportCard";

export default function Reports() {
  const [reports, setReports] = useState([]);

  useEffect(() => {
    api.get("/api/analysis/history").then((response) => {
      const withReports = response.data.items
        .filter((item) => item.incident_report)
        .map((item) => ({
          id: item.id,
          severity: item.risk_score >= 70 ? "high" : item.risk_score >= 40 ? "medium" : "low",
          report_text: item.incident_report,
        }));
      setReports(withReports);
    });
  }, []);

  return (
    <div className="space-y-8">
      <div>
        <p className="text-xs font-semibold uppercase tracking-[0.32em] text-cyan-700">Incident library</p>
        <h1 className="mt-3 text-4xl font-black text-slate-950">Reports</h1>
        <p className="mt-3 text-sm leading-7 text-slate-500">Incident narratives generated by the AI pipeline and ready for analyst review or handoff.</p>
      </div>
      {reports.length ? (
        <div className="grid gap-4 md:grid-cols-2">
          {reports.map((report) => (
            <ReportCard key={report.id} report={report} />
          ))}
        </div>
      ) : (
        <div className="glass-panel rounded-[30px] px-6 py-10 text-center">
          <h2 className="text-xl font-semibold text-slate-950">No reports available yet</h2>
          <p className="mt-3 text-sm leading-6 text-slate-500">Generate a report from any analysis detail page and it will appear here.</p>
        </div>
      )}
    </div>
  );
}
